WITH CLOB_DATA AS (
  SELECT TEXT_ID AS ID, UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(TEXT_DATA, 4000, 1)) AS CLOB_TEXT
  FROM TEXTS
  WHERE TEXT_ID IN (&id_list)
),
LINE_SPLIT AS (
  SELECT ID, CLOB_TEXT, REGEXP_SUBSTR(CLOB_TEXT, '[^' || CHR(10) || ']+', 1, LEVEL) AS line, LEVEL AS LINE_NUM
  FROM CLOB_DATA
  CONNECT BY PRIOR ID = ID AND PRIOR dbms_random.value IS NOT NULL AND LEVEL <= LENGTH(CLOB_TEXT) - LENGTH(REPLACE(CLOB_TEXT, CHR(10), '')) + 1
),
WORD_SPLIT AS (
  SELECT ID, LINE_NUM, REGEXP_SUBSTR(line, '[^[:space:]]+', 1, LEVEL) AS WORD, LEVEL AS WORD_POS, line
  FROM LINE_SPLIT
  CONNECT BY PRIOR ID = ID AND PRIOR LINE_NUM = LINE_NUM AND PRIOR dbms_random.value IS NOT NULL AND LEVEL <= LENGTH(line) - LENGTH(REPLACE(line, ' ', '')) + 1
)
SELECT 
  ID,
  WORD,
  LINE_NUM AS WORD_ROW,
  INSTR(line, WORD, 1, WORD_POS) AS WORD_COLUMN
FROM WORD_SPLIT
WHERE word IS NOT NULL
ORDER BY ID, WORD_ROW, WORD_COLUMN