WITH CLOB_DATA AS (
  SELECT TEXT_ID AS ID, 
         UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(TEXT_DATA, DBMS_LOB.GETLENGTH(TEXT_DATA), 1)) AS CLOB_TEXT
  FROM TEXTS
),
PARAGRAPH_SPLIT AS (
    SELECT ID,
           REGEXP_SUBSTR(CLOB_TEXT,'(.*?)(' || CHR(10)||CHR(13)||'|$)', 1, LEVEL, 'n', 1) AS PARAGRAPH,
           LEVEL AS PARAGRAPH_NUM
    FROM CLOB_DATA
    CONNECT BY PRIOR ID = ID
           AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL
           AND LEVEL < REGEXP_COUNT(CLOB_TEXT, '(.*?)(' || CHR(10)||CHR(13)||'|$)')
),
LINE_SPLIT AS (
  SELECT ID,
         PARAGRAPH,
         PARAGRAPH_NUM,
         REGEXP_SUBSTR(PARAGRAPH, '([^' || CHR(10) || '.]+[.' || CHR(10) || ']?)', 1, LEVEL) AS LINE,
         LEVEL AS LINE_NUM
  FROM PARAGRAPH_SPLIT
  CONNECT BY PRIOR ID = ID
         AND PRIOR PARAGRAPH_NUM = PARAGRAPH_NUM
         AND PRIOR SYS_GUID() IS NOT NULL
         AND REGEXP_SUBSTR(PARAGRAPH, '([^' || CHR(10) || '.]+[.' || CHR(10) || ']?)', 1, LEVEL) IS NOT NULL
),
HIGHLIGHTED_LINE AS (
  SELECT ID,
         PARAGRAPH_NUM,
         LINE_NUM,
         CASE 
           WHEN PARAGRAPH_NUM = :varX AND LINE_NUM = :varY THEN '<<' || LINE || '>>'
           ELSE LINE
         END AS HIGHLIGHTED_LINE
  FROM LINE_SPLIT
),
RECONSTRUCTED_PARAGRAPHS AS (
  SELECT ID,
         PARAGRAPH_NUM,
         LISTAGG(HIGHLIGHTED_LINE, NULL) WITHIN GROUP (ORDER BY LINE_NUM) AS RECONSTRUCTED_PARAGRAPH
  FROM HIGHLIGHTED_LINE
  GROUP BY ID, PARAGRAPH_NUM
),
FINAL_TEXT AS (
  SELECT ID,
         LISTAGG(RECONSTRUCTED_PARAGRAPH || CHR(10) || CHR(13), CHR(10)) WITHIN GROUP (ORDER BY PARAGRAPH_NUM) AS FULL_TEXT
  FROM RECONSTRUCTED_PARAGRAPHS
  GROUP BY ID
)
SELECT ID AS TEXT_ID, FULL_TEXT AS TEXT_DATA
FROM FINAL_TEXT
WHERE ID = :textId