WITH CLOB_DATA AS (
  SELECT TEXT_ID AS ID, 
         UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(TEXT_DATA, DBMS_LOB.GETLENGTH(TEXT_DATA), 1)) AS CLOB_TEXT
  FROM TEXTS
),
LINE_SPLIT AS (
  SELECT ID,
         CLOB_TEXT,
         REGEXP_SUBSTR(CLOB_TEXT, '[^' || CHR(10) || ']+', 1, LEVEL) AS LINE,
         LEVEL AS LINE_NUM
  FROM CLOB_DATA
  CONNECT BY PRIOR ID = ID
         AND PRIOR dbms_random.value IS NOT NULL
         AND LEVEL <= LENGTH(CLOB_TEXT) - LENGTH(REPLACE(CLOB_TEXT, CHR(10), '')) + 1
),
WORD_SPLIT AS (
  SELECT ID, 
         LINE_NUM, 
         REGEXP_SUBSTR(LINE, '[^[:space:]]+', 1, LEVEL) AS WORD, 
         LEVEL AS WORD_POS, 
         LINE
  FROM LINE_SPLIT
  CONNECT BY PRIOR ID = ID 
         AND PRIOR LINE_NUM = LINE_NUM 
         AND PRIOR dbms_random.value IS NOT NULL 
         AND LEVEL <= LENGTH(LINE) - LENGTH(REPLACE(LINE, ' ', '')) + 1
)
SELECT 
  ID AS TEXT_ID,
  WORD,
  LINE_NUM AS WORD_ROW,
  WORD_POS AS WORD_COLUMN
FROM WORD_SPLIT
WHERE WORD IS NOT NULL
  AND LINE_NUM = :varX
  AND WORD_POS = :varY
ORDER BY TEXT_ID, WORD_ROW, WORD_COLUMN